---
title: "test"
format: pdf
bibliography: library.bib
---

## Quarto

One of the current environmental concerns is related to the disposal of plastic waste. The micro- / meso- plastics in the oceans will overweight the global stock of fish based on the projections by 2050. More critically, the global plastic production is expected to increase to 850 million tons per year by the same year. The societal awareness on plastic recycling have received an important attention by scientific, policymaker and general public. Unfortunately, the statistical analysis on the centralized recycling process proves that the valorization is far from being an efficient technique [@Ren2020] and only 9% of the plastic have been recycling from the total stock produced since 1950’s [@Geyer2017]. Therefore, it remains an open challenge to propose additional alternatives to valorize the discarded plastic material. In the same line, the manufacturing technologies needs to integrated since the early conception phase, the use of recycled material as a mitigation strategy of the global impact on the ecosystem.


\newpage


## References

